### add project
POST http://localhost:8080/project/sales
Content-Type: application/json

{
  "name": "남양주 21년 신축 아파트 풍동 프로젝트",
  "alias": "남양신21",
  "receptionManagerId": 1,
  "progressStatus": "TEMPORARY",
  "bidType": "DEFAULT",
  "memo": "견적 의뢰처: 미정\n 소개자: 직접 전화\n총 동수: 4\n단지 수: 1\n기타: 빠르게 시작할 수 있으면 함"
}

### update project
PATCH http://localhost:8080/project/sales/2/basic
Content-Type: application/json

{
  "projectManagerId": 1,
  "salesManagerId": 2,
  "bidType": "G2B",
  "isLh": true
}

### update project status
PATCH http://localhost:8080/project/sales/2/status
Content-Type: application/json

{
  "progressStatus": "UNDER_CONTRACT",
  "estimateExpectation": "HIGH"
}

### get
GET http://localhost:8080/project/sales

### get
GET http://localhost:8080/project/sales/2