### get list
GET http://localhost:8080/project/sales/1/rival-estimate

### push rival estimate
POST http://localhost:8080/project/sales/1/rival-estimate

### update rival estimate 1
PATCH http://localhost:8080/project/sales/rival-estimate/1
Content-Type: application/json

{
  "businessId": 2,
  "testAmount": 15000,
  "reviewAmount": 1500,
  "totalAmount": 16500
}

### delete rival estimate 2
DELETE http://localhost:8080/project/sales/rival-estimate/2
