### department ###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "한양풍동실험연구소",
  "category": "COMPANY"
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "기술",
  "category": "HQ",
  "parentId": 1
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "기술",
  "category": "TEAM",
  "parentId": 2
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "영업",
  "category": "TEAM",
  "parentId": 2
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "모형",
  "category": "TEAM",
  "parentId": 2
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "기술",
  "category": "PART",
  "parentId": 3
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "실험",
  "category": "PART",
  "parentId": 3
}

###
POST http://localhost:8080/departments
Content-Type: application/json

{
  "name": "편집",
  "category": "PART",
  "parentId": 3
}
