### get new count
GET http://localhost:8080/user-notification/count

### get all list
GET http://localhost:8080/user-notification

### read 1
POST http://localhost:8080/user-notification/2

### delete
DELETE  http://localhost:8080/user-notification/2