version: "3"

services:
    db:
        build:
            context: db
            dockerfile: DockerFiles
        ports:
            - "3304:3306"
        volumes:
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        env_file: db/.env
        environment:
            TZ: Asia/Seoul
        restart: always
#    app:
#        build:
#            context: .
#            dockerfile: DockerFiles
#        ports:
#            - '8080:8080'
#        working_dir: /app
#        command:
#            - "bash"
#            - "-c"
#            - "./app/wait-for-it.sh db:3306 --java -jar ./app/build/libs/app-0.0.1-SNAPSHOT.war"
