# TODO: customize this file
spring:
    datasource:
        url: jdbc:mysql://localhost:3304/hywtl_has_api?useSSL=false
        username: hywtl_has
        password: hywtl_has7698
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate.cache.region_prefix: local

application:
    front-url: http://localhost:8080
    mail:
        invalidate-duration: P180D
        username: caster@howoocast.com
        password: zozo@123123
        host: smtp.office365.com
        port: 587
        auth: true
        starttls: true
        name: 발송자
        dev-receiver: woo@howoocast.com
    file:
        root-path: D:/temp/hywtl_has_files

logging:
    level:
        root: INFO
        web: DEBUG
        com.howoocast: DEBUG

server:
    port: 8080