server:
    port: 8080

logging:
    level:
        root: INFO
        web: DEBUG
        com.howoocast: DEBUG

spring:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    thymeleaf:
        cache: false
    sql:
        init:
            mode: always
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3304/hywtl_has_api
        username: hywtl_has
        password: hywtl_has7698
        hikari:
            pool-name: hikariPool
            auto-commit: false
            connection-timeout: 1000 #ms
            max-lifetime: 58000 #ms
            idle-timeout: 0
            maximum-pool-size: 5
            minimum-idle: 5
            leak-detection-threshold: 2000 # ms
            data-source-properties:
                cachePrepStmts: true
                useServerPrepStmts: true
                prepStmtCacheSize: 500
                prepStmtCacheSqlLimit: 2048
    jpa:
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate.format_sql: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.use_reference_entries: true
            hibernate.cache.default_cache_concurrency_strategy: nonstrict-read-write
            hibernate.cache.region_prefix: local
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
        defer-datasource-initialization: true
    profiles:
        active: local

application:
    front-url: http://localhost:8080
    mail:
        invalidate-duration: PT1H
        username: caster@howoocast.com
        password: zozo@123123
        host: smtp.office365.com
        port: 587
        auth: true
        starttls: true
        name: 발송자
        dev-receiver: young@howoocast.com