set FOREIGN_KEY_CHECKS = 0;
drop table if exists company;
drop table if exists company_manager_list;
drop table if exists department;
drop table if exists file_item;
drop table if exists manager;
drop table if exists password_reset;
drop table if exists personnel;
drop table if exists personnel_academic_list;
drop table if exists personnel_career_list;
drop table if exists personnel_job;
drop table if exists personnel_job_list;
drop table if exists personnel_language_list;
drop table if exists personnel_license_list;
drop table if exists project;
drop table if exists project_comment;
drop table if exists project_target_document;
drop table if exists project_target_review;
drop table if exists project_target_review_detail;
drop table if exists project_target_review_detail_list;
drop table if exists project_target_review_detail_special_wind_load_condition_list;
drop table if exists project_target_review_detail_test_list;
drop table if exists user;
drop table if exists user_invitation;
set FOREIGN_KEY_CHECKS = 1;