set FOREIGN_KEY_CHECKS = 0;
truncate table department;
truncate table file_item;
truncate table personnel;
truncate table personnel_academic_list;
truncate table personnel_career_list;
truncate table personnel_job;
truncate table personnel_job_list;
truncate table personnel_language_list;
truncate table personnel_license_list;
truncate table user;
truncate table user_invitation;

alter table department auto_increment = 1;
alter table file_item auto_increment = 1;
alter table personnel auto_increment = 1;
alter table personnel_academic_list auto_increment = 1;
alter table personnel_career_list auto_increment = 1;
alter table personnel_job auto_increment = 1;
alter table personnel_job_list auto_increment = 1;
alter table personnel_language_list auto_increment = 1;
alter table personnel_license_list auto_increment = 1;
alter table user auto_increment = 1;
alter table user_invitation auto_increment = 1;
set FOREIGN_KEY_CHECKS = 1;